### ISSUE TITLE
似乎不能调用zeal?

### ISSUE THREAD

**Issue by musicwei** [fofolee/uTools-Manuals#2]
是不是目前支持调用dash，但是还不支持调用zeal？

**Comment by fofolee** [comment]
可以调用，参考更新说明里的介绍

**Comment by fofolee** [comment]
> 可以调用，参考更新说明里的介绍

第一次启用插件时无法调用。。。是一个BUG，现已修复

**Comment by cicada-lewis** [comment]
我也遇到了这样的情况， 似乎是调用zeal命令的时候没有成功

**Comment by cicada-lewis** [comment]
报错 bash/sh:1 open:not found

**Comment by fofolee** [comment]
> 报错 bash/sh:1 open:not found

其实是我并不知道linux下也有zeal、、、现在更新了下，在kali下测试通过，你可以试试

**Comment by cicada-lewis** [comment]
在ubuntu18.04下 只是弹出了通知，可以让zeal弹出吗？

**Comment by fofolee** [comment]
> 在ubuntu18.04下 只是弹出了通知，可以让zeal弹出吗？

我在kali和deepin下均可以正常打开zeal，试下删掉已有版本，手动在插件中心下载新版本，如还不行，在终端测试下如下语句
zeal dash://bash:ls
